### ISSUE TITLE
Return type of Poly.points

### ISSUE THREAD

**Issue by gogo55** [qwertyquerty/collision#4]
The return type of points is "list of Vector2".
Has this a reason? Isn't better to return "list of Vector" (eg Vector2 has no copy() method)?
Somehow this breaks the architecture... For example I cannot (easily) construct a new Poly out of existing Poly.points.

I also miss the possibility to construct Vector as Vector(Vector).
Regards
Gogo

**Comment by qwertyquerty** [comment]
This is not the case.
